In [59]:
import numpy as np
import image

In [60]:
import cv2

In [61]:
img1 = cv2.imread(r'D:\BTP\0b2dae8928e178f368b6d152a1367b7f--cats-meowing-kitty-cats.jpg')
img2 = cv2.imread(r'D:\BTP\cat_shredder0714.jpg')

In [62]:
img1.shape , img2.shape

((400, 400, 3), (400, 400, 3))

In [63]:
cv2.imshow('img' ,img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [64]:
cv2.imshow('img' ,img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
input_img = np.concatenate(([img1],[img2]), axis=0)

In [66]:
print("Input Img Shape: {}".format(input_img.shape))

Input Img Shape: (2, 400, 400, 3)


In [67]:
num_batch, H, W, C = input_img.shape

In [68]:
M = np.array([[0.707, -0.707, 0.], [0.707, 0.707, 0.]])

In [69]:
M = np.resize(M, (num_batch, 2, 3))
M

array([[[ 0.707, -0.707,  0.   ],
        [ 0.707,  0.707,  0.   ]],

       [[ 0.707, -0.707,  0.   ],
        [ 0.707,  0.707,  0.   ]]])

In [70]:
x = np.linspace(-1, 1, W)
y = np.linspace(-1, 1, H)
x_t, y_t = np.meshgrid(x, y)

In [71]:
x_t

array([[-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       ...,
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ]])

In [72]:
y_t

array([[-1.        , -1.        , -1.        , ..., -1.        ,
        -1.        , -1.        ],
       [-0.99498747, -0.99498747, -0.99498747, ..., -0.99498747,
        -0.99498747, -0.99498747],
       [-0.98997494, -0.98997494, -0.98997494, ..., -0.98997494,
        -0.98997494, -0.98997494],
       ...,
       [ 0.98997494,  0.98997494,  0.98997494, ...,  0.98997494,
         0.98997494,  0.98997494],
       [ 0.99498747,  0.99498747,  0.99498747, ...,  0.99498747,
         0.99498747,  0.99498747],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ]])

In [73]:
ones = np.ones(np.prod(x_t.shape))

In [74]:
ones.shape

(160000,)

In [75]:
sampling_grid = np.vstack([x_t.flatten(), y_t.flatten(), ones])

In [76]:
sampling_grid.shape

(3, 160000)

In [77]:
sampling_grid = np.resize(sampling_grid, (num_batch, 3, H*W))

In [78]:
sampling_grid.shape

(2, 3, 160000)

In [79]:

batch_grids = np.matmul(M, sampling_grid)

In [80]:
batch_grids.shape

(2, 2, 160000)

In [81]:
batch_grids = batch_grids.reshape(num_batch, 2, H, W)

In [82]:
batch_grids.shape

(2, 2, 400, 400)

In [83]:
batch_grids = np.moveaxis(batch_grids, 1, -1)

In [84]:
batch_grids.shape

(2, 400, 400, 2)

In [85]:
x_s = batch_grids[:, :, :, 0:1].squeeze()
y_s = batch_grids[:, :, :, 1:2].squeeze()


In [86]:
x_s

array([[[ 0.        ,  0.00354386,  0.00708772, ...,  1.40691228,
          1.41045614,  1.414     ],
        [-0.00354386,  0.        ,  0.00354386, ...,  1.40336842,
          1.40691228,  1.41045614],
        [-0.00708772, -0.00354386,  0.        , ...,  1.39982456,
          1.40336842,  1.40691228],
        ...,
        [-1.40691228, -1.40336842, -1.39982456, ...,  0.        ,
          0.00354386,  0.00708772],
        [-1.41045614, -1.40691228, -1.40336842, ..., -0.00354386,
          0.        ,  0.00354386],
        [-1.414     , -1.41045614, -1.40691228, ..., -0.00708772,
         -0.00354386,  0.        ]],

       [[ 0.        ,  0.00354386,  0.00708772, ...,  1.40691228,
          1.41045614,  1.414     ],
        [-0.00354386,  0.        ,  0.00354386, ...,  1.40336842,
          1.40691228,  1.41045614],
        [-0.00708772, -0.00354386,  0.        , ...,  1.39982456,
          1.40336842,  1.40691228],
        ...,
        [-1.40691228, -1.40336842, -1.39982456, ...,  

In [87]:
y_s

array([[[-1.41400000e+00, -1.41045614e+00, -1.40691228e+00, ...,
         -7.08771930e-03, -3.54385965e-03,  0.00000000e+00],
        [-1.41045614e+00, -1.40691228e+00, -1.40336842e+00, ...,
         -3.54385965e-03,  0.00000000e+00,  3.54385965e-03],
        [-1.40691228e+00, -1.40336842e+00, -1.39982456e+00, ...,
         -2.22044605e-16,  3.54385965e-03,  7.08771930e-03],
        ...,
        [-7.08771930e-03, -3.54385965e-03, -2.22044605e-16, ...,
          1.39982456e+00,  1.40336842e+00,  1.40691228e+00],
        [-3.54385965e-03,  0.00000000e+00,  3.54385965e-03, ...,
          1.40336842e+00,  1.40691228e+00,  1.41045614e+00],
        [ 0.00000000e+00,  3.54385965e-03,  7.08771930e-03, ...,
          1.40691228e+00,  1.41045614e+00,  1.41400000e+00]],

       [[-1.41400000e+00, -1.41045614e+00, -1.40691228e+00, ...,
         -7.08771930e-03, -3.54385965e-03,  0.00000000e+00],
        [-1.41045614e+00, -1.40691228e+00, -1.40336842e+00, ...,
         -3.54385965e-03,  0.00000000e

In [88]:
x = ((x_s + 1.) * W) * 0.5
y = ((y_s + 1.) * H) * 0.5

In [89]:
x.shape

(2, 400, 400)

In [90]:
x

array([[[200.        , 200.70877193, 201.41754386, ..., 481.38245614,
         482.09122807, 482.8       ],
        [199.29122807, 200.        , 200.70877193, ..., 480.67368421,
         481.38245614, 482.09122807],
        [198.58245614, 199.29122807, 200.        , ..., 479.96491228,
         480.67368421, 481.38245614],
        ...,
        [-81.38245614, -80.67368421, -79.96491228, ..., 200.        ,
         200.70877193, 201.41754386],
        [-82.09122807, -81.38245614, -80.67368421, ..., 199.29122807,
         200.        , 200.70877193],
        [-82.8       , -82.09122807, -81.38245614, ..., 198.58245614,
         199.29122807, 200.        ]],

       [[200.        , 200.70877193, 201.41754386, ..., 481.38245614,
         482.09122807, 482.8       ],
        [199.29122807, 200.        , 200.70877193, ..., 480.67368421,
         481.38245614, 482.09122807],
        [198.58245614, 199.29122807, 200.        , ..., 479.96491228,
         480.67368421, 481.38245614],
        ...,


In [91]:
y

array([[[-82.8       , -82.09122807, -81.38245614, ..., 198.58245614,
         199.29122807, 200.        ],
        [-82.09122807, -81.38245614, -80.67368421, ..., 199.29122807,
         200.        , 200.70877193],
        [-81.38245614, -80.67368421, -79.96491228, ..., 200.        ,
         200.70877193, 201.41754386],
        ...,
        [198.58245614, 199.29122807, 200.        , ..., 479.96491228,
         480.67368421, 481.38245614],
        [199.29122807, 200.        , 200.70877193, ..., 480.67368421,
         481.38245614, 482.09122807],
        [200.        , 200.70877193, 201.41754386, ..., 481.38245614,
         482.09122807, 482.8       ]],

       [[-82.8       , -82.09122807, -81.38245614, ..., 198.58245614,
         199.29122807, 200.        ],
        [-82.09122807, -81.38245614, -80.67368421, ..., 199.29122807,
         200.        , 200.70877193],
        [-81.38245614, -80.67368421, -79.96491228, ..., 200.        ,
         200.70877193, 201.41754386],
        ...,


In [92]:
x0 = np.floor(x).astype(np.int64)
x1 = x0 + 1
y0 = np.floor(y).astype(np.int64)
y1 = y0 + 1

In [93]:
x0

array([[[200, 200, 201, ..., 481, 482, 482],
        [199, 200, 200, ..., 480, 481, 482],
        [198, 199, 200, ..., 479, 480, 481],
        ...,
        [-82, -81, -80, ..., 200, 200, 201],
        [-83, -82, -81, ..., 199, 200, 200],
        [-83, -83, -82, ..., 198, 199, 200]],

       [[200, 200, 201, ..., 481, 482, 482],
        [199, 200, 200, ..., 480, 481, 482],
        [198, 199, 200, ..., 479, 480, 481],
        ...,
        [-82, -81, -80, ..., 200, 200, 201],
        [-83, -82, -81, ..., 199, 200, 200],
        [-83, -83, -82, ..., 198, 199, 200]]], dtype=int64)

In [94]:
x0 = np.clip(x0, 0, W-1)
x1 = np.clip(x1, 0, W-1)
y0 = np.clip(y0, 0, H-1)
y1 = np.clip(y1, 0, H-1)

In [95]:
x0.shape

(2, 400, 400)

In [96]:
x0

array([[[200, 200, 201, ..., 399, 399, 399],
        [199, 200, 200, ..., 399, 399, 399],
        [198, 199, 200, ..., 399, 399, 399],
        ...,
        [  0,   0,   0, ..., 200, 200, 201],
        [  0,   0,   0, ..., 199, 200, 200],
        [  0,   0,   0, ..., 198, 199, 200]],

       [[200, 200, 201, ..., 399, 399, 399],
        [199, 200, 200, ..., 399, 399, 399],
        [198, 199, 200, ..., 399, 399, 399],
        ...,
        [  0,   0,   0, ..., 200, 200, 201],
        [  0,   0,   0, ..., 199, 200, 200],
        [  0,   0,   0, ..., 198, 199, 200]]], dtype=int64)

In [97]:
np.arange(num_batch)[:,None,None].shape

(2, 1, 1)

In [98]:
Ia = input_img[np.arange(num_batch)[:,None,None], y0, x0]
Ib = input_img[np.arange(num_batch)[:,None,None], y1, x0]
Ic = input_img[np.arange(num_batch)[:,None,None], y0, x1]
Id = input_img[np.arange(num_batch)[:,None,None], y1, x1]

In [99]:
input_img[np.arange(num_batch)[:,None,None], y0, x0].shape

(2, 400, 400, 3)

In [100]:
Ia.shape

(2, 400, 400, 3)

In [101]:
Ia

array([[[[183, 185, 179],
         [183, 185, 179],
         [183, 185, 179],
         ...,
         [ 83,  77,  72],
         [ 79,  73,  68],
         [ 79,  73,  68]],

        [[182, 184, 178],
         [183, 185, 179],
         [183, 185, 179],
         ...,
         [ 79,  73,  68],
         [ 79,  73,  68],
         [ 79,  73,  68]],

        [[182, 184, 178],
         [182, 184, 178],
         [183, 185, 179],
         ...,
         [ 79,  73,  68],
         [ 79,  73,  68],
         [ 73,  67,  62]],

        ...,

        [[205, 201, 196],
         [207, 203, 198],
         [207, 203, 198],
         ...,
         [194, 194, 194],
         [194, 194, 194],
         [194, 194, 194]],

        [[207, 203, 198],
         [203, 200, 195],
         [203, 200, 195],
         ...,
         [194, 194, 194],
         [194, 194, 194],
         [194, 194, 194]],

        [[203, 200, 195],
         [203, 200, 195],
         [196, 196, 190],
         ...,
         [194, 194, 194],
        

In [102]:
wa = (x1-x) * (y1-y)
wb = (x1-x) * (y-y0)
wc = (x-x0) * (y1-y)
wd = (x-x0) * (y-y0)

In [103]:
wa.shape

(2, 400, 400)

In [104]:
wa[:,:,:,None]

array([[[[ 8.28000000e+01],
         [ 2.39072699e+01],
         [ 4.74017113e+01],
         ...,
         [-3.43982887e+01],
         [-5.88927301e+01],
         [-8.38000000e+01]],

        [[ 5.81839581e+01],
         [ 8.13824561e+01],
         [ 2.34944414e+01],
         ...,
         [-5.78880148e+01],
         [-8.23824561e+01],
         [-2.41984980e+01]],

        [[ 3.39807448e+01],
         [ 5.71792428e+01],
         [ 7.99649123e+01],
         ...,
         [-4.60232242e-12],
         [-2.37856694e+01],
         [-4.79841674e+01]],

        ...,

        [[ 3.39807448e+01],
         [ 5.71792428e+01],
         [ 4.54547900e-12],
         ...,
         [-8.09649123e+01],
         [-2.37856694e+01],
         [-4.79841674e+01]],

        [[ 5.81839581e+01],
         [ 8.13824561e+01],
         [ 2.34944414e+01],
         ...,
         [-5.78880148e+01],
         [-8.23824561e+01],
         [-2.41984980e+01]],

        [[ 8.28000000e+01],
         [ 2.39072699e+01],
         [

In [105]:
wa = np.expand_dims(wa, axis=3)
wb = np.expand_dims(wb, axis=3)
wc = np.expand_dims(wc, axis=3)
wd = np.expand_dims(wd, axis=3)

In [106]:
wa.shape

(2, 400, 400, 1)

In [107]:
wa

array([[[[ 8.28000000e+01],
         [ 2.39072699e+01],
         [ 4.74017113e+01],
         ...,
         [-3.43982887e+01],
         [-5.88927301e+01],
         [-8.38000000e+01]],

        [[ 5.81839581e+01],
         [ 8.13824561e+01],
         [ 2.34944414e+01],
         ...,
         [-5.78880148e+01],
         [-8.23824561e+01],
         [-2.41984980e+01]],

        [[ 3.39807448e+01],
         [ 5.71792428e+01],
         [ 7.99649123e+01],
         ...,
         [-4.60232242e-12],
         [-2.37856694e+01],
         [-4.79841674e+01]],

        ...,

        [[ 3.39807448e+01],
         [ 5.71792428e+01],
         [ 4.54547900e-12],
         ...,
         [-8.09649123e+01],
         [-2.37856694e+01],
         [-4.79841674e+01]],

        [[ 5.81839581e+01],
         [ 8.13824561e+01],
         [ 2.34944414e+01],
         ...,
         [-5.78880148e+01],
         [-8.23824561e+01],
         [-2.41984980e+01]],

        [[ 8.28000000e+01],
         [ 2.39072699e+01],
         [

In [108]:
out = wa*Ia + wb*Ib + wc*Ic + wd*Id

In [109]:
out.shape

(2, 400, 400, 3)

In [110]:
img1[:,-3,:]

array([[196, 196, 184],
       [196, 196, 184],
       [196, 196, 184],
       ...,
       [163, 159, 158],
       [163, 159, 158],
       [163, 159, 158]], dtype=uint8)

In [111]:
img1

array([[[187, 185, 174],
        [189, 187, 176],
        [192, 190, 179],
        ...,
        [196, 196, 184],
        [193, 193, 179],
        [185, 185, 171]],

       [[187, 185, 174],
        [189, 187, 176],
        [192, 190, 179],
        ...,
        [196, 196, 184],
        [193, 193, 179],
        [185, 185, 171]],

       [[187, 185, 174],
        [189, 187, 176],
        [192, 190, 179],
        ...,
        [196, 196, 184],
        [193, 193, 179],
        [185, 185, 171]],

       ...,

       [[112, 124, 124],
        [115, 127, 127],
        [118, 130, 130],
        ...,
        [163, 159, 158],
        [163, 159, 158],
        [163, 159, 158]],

       [[113, 126, 124],
        [115, 128, 126],
        [118, 131, 129],
        ...,
        [163, 159, 158],
        [163, 159, 158],
        [163, 159, 158]],

       [[112, 125, 123],
        [115, 128, 126],
        [117, 130, 128],
        ...,
        [163, 159, 158],
        [163, 159, 158],
        [163, 159, 158]]

In [112]:
out[0].astype(np.uint8)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [113]:
a = out[0].astype(np.uint8)
cv2.imshow('img_mod',a)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
def _repeat(x, n_repeats):
    rep = tf.transpose(
      tf.expand_dims(tf.ones(shape=tf.stack([n_repeats, ])), 1), [1, 0])
    rep = tf.cast(rep, 'int32')
    x = tf.matmul(tf.reshape(x, (-1, 1)), rep)
    return tf.reshape(x, [-1])

In [2]:
import tensorflow as tf

In [3]:
tf.stack([4])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4])>

In [4]:
tf.stack([4, ])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4])>

In [5]:
tf.constant([4])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4])>

In [6]:
tf.ones(shape=tf.stack([4, ]))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [7]:
tf.expand_dims(tf.ones(shape=tf.stack([4, ])), 1)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [8]:
rep = tf.transpose(
      tf.expand_dims(tf.ones(shape=tf.stack([4, ])), 1), [1, 0])

In [9]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])

In [10]:
x

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [11]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])>

In [12]:
tf.transpose(x, perm=[0, 2, 1])

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])>

In [13]:
rep = tf.cast(rep, 'int32')

In [14]:
rep


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 1, 1, 1]])>

In [20]:
tf.reshape(x, (-1, 1))

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])>

In [23]:
x = tf.matmul(tf.reshape(x, (-1, 1)), rep)

In [24]:
x

<tf.Tensor: shape=(12, 4), dtype=int32, numpy=
array([[ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 3,  3,  3,  3],
       [ 4,  4,  4,  4],
       [ 5,  5,  5,  5],
       [ 6,  6,  6,  6],
       [ 7,  7,  7,  7],
       [ 8,  8,  8,  8],
       [ 9,  9,  9,  9],
       [10, 10, 10, 10],
       [11, 11, 11, 11],
       [12, 12, 12, 12]])>

In [25]:
tf.reshape(x, [-1])

<tf.Tensor: shape=(48,), dtype=int32, numpy=
array([ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,
        5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12])>

In [15]:
def _interpolate(im, x, y, out_size):
    # constants
    num_batch = tf.shape(im)[0]
    height = tf.shape(im)[1]
    width = tf.shape(im)[2]
    channels = tf.shape(im)[3]

    x = tf.cast(x, 'float32')
    y = tf.cast(y, 'float32')
    height_f = tf.cast(height, 'float32')
    width_f = tf.cast(width, 'float32')
    out_height = out_size[0]
    out_width = out_size[1]
    zero = tf.zeros([], dtype='int32')
    max_y = tf.cast(tf.shape(im)[1] - 1, 'int32')
    max_x = tf.cast(tf.shape(im)[2] - 1, 'int32')

    # scale indices from [-1, 1] to [0, width/height]
    x = (x + 1.0)*(width_f) / 2.0
    y = (y + 1.0)*(height_f) / 2.0

    # do sampling
    x0 = tf.cast(tf.floor(x), 'int32')
    x1 = x0 + 1
    y0 = tf.cast(tf.floor(y), 'int32')
    y1 = y0 + 1

    x0 = tf.clip_by_value(x0, zero, max_x)
    x1 = tf.clip_by_value(x1, zero, max_x)
    y0 = tf.clip_by_value(y0, zero, max_y)
    y1 = tf.clip_by_value(y1, zero, max_y)
    dim2 = width
    dim1 = width*height
    base = _repeat(tf.range(num_batch)*dim1, out_height*out_width)
    base_y0 = base + y0*dim2
    base_y1 = base + y1*dim2
    idx_a = base_y0 + x0
    idx_b = base_y1 + x0
    idx_c = base_y0 + x1
    idx_d = base_y1 + x1

    # use indices to lookup pixels in the flat image and restore
    # channels dim
    im_flat = tf.reshape(im, tf.stack([-1, channels]))
    im_flat = tf.cast(im_flat, 'float32')
    Ia = tf.gather(im_flat, idx_a)
    Ib = tf.gather(im_flat, idx_b)
    Ic = tf.gather(im_flat, idx_c)
    Id = tf.gather(im_flat, idx_d)

    # and finally calculate interpolated values
    x0_f = tf.cast(x0, 'float32')
    x1_f = tf.cast(x1, 'float32')
    y0_f = tf.cast(y0, 'float32')
    y1_f = tf.cast(y1, 'float32')
    wa = tf.expand_dims(((x1_f-x) * (y1_f-y)), 1)
    wb = tf.expand_dims(((x1_f-x) * (y-y0_f)), 1)
    wc = tf.expand_dims(((x-x0_f) * (y1_f-y)), 1)
    wd = tf.expand_dims(((x-x0_f) * (y-y0_f)), 1)
    output = tf.add_n([wa*Ia, wb*Ib, wc*Ic, wd*Id])
    return output

In [ ]:
 def _meshgrid(height, width, source):
    x_t = tf.tile(
      tf.reshape(tf.linspace(-1.0, 1.0, width), [1, width]), [height, 1])
    y_t = tf.tile(
      tf.reshape(tf.linspace(-1.0, 1.0, height), [height, 1]), [1, width])

    x_t_flat = tf.reshape(x_t, (1, 1, -1))
    y_t_flat = tf.reshape(y_t, (1, 1, -1))

    num_batch = tf.shape(source)[0]
    px = tf.expand_dims(source[:,:,0], 2) # [bn, pn, 1]
    py = tf.expand_dims(source[:,:,1], 2) # [bn, pn, 1]
    d2 = tf.square(x_t_flat - px) + tf.square(y_t_flat - py)
    r = d2 * tf.log(d2 + 1e-6) # [bn, pn, h*w]
    x_t_flat_g = tf.tile(x_t_flat, tf.stack([num_batch, 1, 1])) # [bn, 1, h*w]
    y_t_flat_g = tf.tile(y_t_flat, tf.stack([num_batch, 1, 1])) # [bn, 1, h*w]
    ones = tf.ones_like(x_t_flat_g) # [bn, 1, h*w]

    grid = tf.concat([ones, x_t_flat_g, y_t_flat_g, r], 1) # [bn, 3+pn, h*w]
    return grid